/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webrtc_ns_AudioProcessJni */

#ifndef _Included_com_webrtc_ns_AudioProcessJni
#define _Included_com_webrtc_ns_AudioProcessJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webrtc_ns_AudioProcessJni
 * Method:    initiateNSInstance
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_com_webrtc_ns_AudioProcessJni_initiateNSInstance
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     com_webrtc_ns_AudioProcessJni
 * Method:    processNS
 * Signature: (I[S[S[S[S)I
 */
JNIEXPORT jint JNICALL Java_com_webrtc_ns_AudioProcessJni_processNS
  (JNIEnv *, jclass, jint, jshortArray, jshortArray, jshortArray, jshortArray);

/*
 * Class:     com_webrtc_ns_AudioProcessJni
 * Method:    destoryNS
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_webrtc_ns_AudioProcessJni_destoryNS
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_webrtc_ns_AudioProcessJni
 * Method:    AgcFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_webrtc_ns_AudioProcessJni_AgcFree
  (JNIEnv *, jclass);

/*
 * Class:     com_webrtc_ns_AudioProcessJni
 * Method:    AgcFun
 * Signature: ([S[SI)I
 */
JNIEXPORT jint JNICALL Java_com_webrtc_ns_AudioProcessJni_AgcFun
  (JNIEnv *, jclass, jshortArray, jshortArray, jint);

/*
 * Class:     com_webrtc_ns_AudioProcessJni
 * Method:    AgcInit
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_webrtc_ns_AudioProcessJni_AgcInit
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_webrtc_ns_AudioProcessJni
 * Method:    setDirectBuffer
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_webrtc_ns_AudioProcessJni_setDirectBuffer
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_webrtc_ns_AudioProcessJni
 * Method:    testDirectBufferContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_webrtc_ns_AudioProcessJni_testDirectBufferContext
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
